### ISSUE TITLE
Spec error "There aren't targets available" on Windows 7

### ISSUE THREAD

**Issue by hyperlexie** [route/ferrum#6]
Hi, I'm using Ferrum 0.2.1 on Windows 7 Professional SP1.  I tried running the first "save a screenshot" example from README.md, and I get the error "There aren't targets available (Ferrum::EmptyTargetsError)"

I get the same error running the specs:

```
C:\ferrum-master>bundle exec rake
C:/Ruby/Ruby255-x64/bin/ruby.exe -I'C:/Ruby/Ruby255-x64/lib/ruby/gems/2.5.0/gems/rspec-core-3.8.2/lib';'C:/Ruby/Ruby255-x64/lib/ruby/g
ems/2.5.0/gems/rspec-support-3.8.2/lib' 'C:/Ruby/Ruby255-x64/lib/ruby/gems/2.5.0/gems/rspec-core-3.8.2/exe/rspec' --pattern 'spec/**{,/*/*
*}/*_spec.rb'
Starting Puma
* Version 4.1.0 , codename: Fourth and One
* Min threads: 0, max threads: 4
* Listening on tcp://127.0.0.1:60259

basic http authentication
  denies without credentials (FAILED - 1)

Failures:

  1) basic http authentication denies without credentials
     Got 0 failures and 2 other errors:

     1.1) Failure/Error: raise EmptyTargetsError if targets.empty?

          Ferrum::EmptyTargetsError:
            There aren't targets available
          # ./lib/ferrum/targets.rb:110:in `block in targets'
          # ./lib/ferrum.rb:95:in `with_attempts'
          # ./lib/ferrum/targets.rb:105:in `targets'
          # ./lib/ferrum/targets.rb:12:in `initialize'
          # ./lib/ferrum/browser.rb:109:in `new'
          # ./lib/ferrum/browser.rb:109:in `targets'
          # ./spec/browser/basic_auth_spec.rb:8:in `block (2 levels) in <module:Ferrum>'

     1.2) Failure/Error: raise EmptyTargetsError if targets.empty?

          Ferrum::EmptyTargetsError:
            There aren't targets available
          # ./lib/ferrum/targets.rb:110:in `block in targets'
          # ./lib/ferrum.rb:95:in `with_attempts'
          # ./lib/ferrum/targets.rb:105:in `targets'
          # ./lib/ferrum/targets.rb:12:in `initialize'
          # ./lib/ferrum/browser.rb:109:in `new'
          # ./lib/ferrum/browser.rb:109:in `targets'
          # ./lib/ferrum/browser.rb:94:in `reset'
          # ./spec/spec_helper.rb:58:in `block (2 levels) in <top (required)>'

Finished in 1.8 seconds (files took 2.23 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/browser/basic_auth_spec.rb:7 # basic http authentication denies without credentials

C:/Ruby/Ruby255-x64/bin/ruby.exe -I'C:/Ruby/Ruby255-x64/lib/ruby/gems/2.5.0/gems/rspec-core-3.8.2/lib';'C:/Ruby/Ruby255-x64/lib/ruby/g
ems/2.5.0/gems/rspec-support-3.8.2/lib' 'C:/Ruby/Ruby255-x64/lib/ruby/gems/2.5.0/gems/rspec-core-3.8.2/exe/rspec' --pattern 'spec/**{,/*/*
*}/*_spec.rb' failed

C:\ferrum-master>ruby -v
ruby 2.5.5p157 (2019-03-15 revision 67260) [x64-mingw32]
```

Thanks for any assistance!

**Comment by route** [comment]
What Chrome version are you using by the way?

**Comment by hyperlexie** [comment]
Version 76.0.3809.132 (Official Build) (64-bit)  (the current version)

I checked, and exactly the same 2 spec failures occur on Windows 10 Pro version 1803 (current fully patched Windows 10 version), same version of Chrome.

**Comment by route** [comment]
Confirming that for some reason Chrome doesn't start properly on Windows 10, but looks like even if I skip this check for targets and we create page it crashes nevertheless, though interesting thing is that when I pass `headless: false` flag Chrome starts...

**Comment by hyperlexie** [comment]
Thanks!  As you pointed out, puppeteer has some similar-sounding issues on Windows.  I'll look into running ferrum on a different OS.

**Comment by route** [comment]
@hyperlexie using branch `gem "ferrum, github:"route/ferrum", branch: "add-contexts"` and this code seems to be fixed the issue:
```ruby
require "ferrum"

browser = Ferrum::Browser.new(browser_path: "C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe", logger: STDOUT, browser_options: { 'no-sandbox': nil })
browser.goto("https://google.com")
browser.screenshot(path: "google.png")
browser.quit
```

I'm going to merge it soon, it's not windows fix, it's added API for contexts.

**Comment by hyperlexie** [comment]
@route WOW!  I tried running your 0.4 gem with the code you provided.

On Windows 7, the first 4 times I got a timeout.  I set timeout: 10, and the next 4 times it ran successfully, producing the google.png file.
I was a little surprised to get the timeouts, as this is a 3 year old laptop that's reasonably fast: Core i7 2.6GHz, 64 GB RAM, 2 SSDs in RAID 0, high speed internet connection.

On Windows 10 (without the :timeout parameter) the first time I got the timeout.  The next time I got "There aren't targets available" (see below), and the next 2 times it ran successfully and produced google.png.  (I never did set the timeout).  Nothing changed between the runs, just run, run, run, run.  I'm guessing the first timeout got resolved by caching somewhere. This is on a 7 year old laptop that's getting pretty sluggish.

I'm very glad to see this basically working.  Thank you!!!

```
▶ 0.9767789228353649 {"method":"Target.getTargets","params":{},"id":2}
    ◀ 0.9909544929396361 {"id":2,"result":{"targetInfos":[]}}


▶ 1.0229625208303332 {"method":"Target.getTargets","params":{},"id":3}
    ◀ 1.1605821179691702 {"id":3,"result":{"targetInfos":[]}}
 (most recent call last):
        8: from C:/Users/hyperlexie/RubymineProjects/ferrum_test_2/main.rb:4:in `<main>'

        7: from C:/Ruby/Ruby250-2-x64/lib/ruby/2.5.0/forwardable.rb:223:in `goto'


        6: from C:/Ruby/Ruby250-2-x64/lib/ruby/2.5.0/forwardable.rb:223:in `page'

        5: from C:/Ruby/Ruby250-2-x64/lib/ruby/gems/2.5.0/gems/ferrum-0.4/lib/ferrum/browser.rb:100:in `targets'
        4: from C:/Ruby/Ruby250-2-x64/lib/ruby/gems/2.5.0/gems/ferrum-0.4/lib/ferrum/browser.rb:100:in `new'
        3: from C:/Ruby/Ruby250-2-x64/lib/ruby/gems/2.5.0/gems/ferrum-0.4/lib/ferrum/targets.rb:12:in `initialize'
        2: from C:/Ruby/Ruby250-2-x64/lib/ruby/gems/2.5.0/gems/ferrum-0.4/lib/ferrum/targets.rb:105:in `targets'
        1: from C:/Ruby/Ruby250-2-x64/lib/ruby/gems/2.5.0/gems/ferrum-0.4/lib/ferrum.rb:110:in `with_attempts'
C:/Ruby/Ruby250-2-x64/lib/ruby/gems/2.5.0/gems/ferrum-0.4/lib/ferrum/targets.rb:110:in `block in targets': There aren't targets available (Ferrum::EmptyTargetsError)

Process finished with exit code 1
```

**Comment by route** [comment]
@hyperlexie I'll release new version soon, it works with targets slightly different so there shouldn't be `EmptyTargetsError` anymore.

The key is `no-sandbox`, I guess timeout option is not needed.

I added it because first time I also got timeout but next run it was fine. From the log I noticed that when Ferrum called `goto` it stuck because it never got response back. Dunno but it is something Chrome + Windows related and doesn't depend on CPU. I have very powerful 8700K but it bit me either.
